### ISSUE TITLE
[s] [A&R Feature Request] mark goldpan park as historical

### ISSUE THREAD

**Issue by nicolebottoms** [bcgov/bcparks-ar-admin#408] opened 2024-11-19 17:11 UTC
Description: goldpan park is closed and is very unlikely to reopen again, can you please mark this park and sub-areas as historic in the system.
thanks!

Context:

Links to other resources/docs:
- https://bcparks.ca/goldpan-park/

Screenshots (if applicable):

Changes:
- ORCS Number: 0063
- Region: thompson cariboo
- Section: thompson
- Management Area: thompson southern rivers
- Bundle: thompson merritt
- Park: goldpan
- Park Sub Area: 0153
- Requested Change: mark goldpan park as historic

**Comment by LindsayMacfarlane** [comment] 2024-11-20 21:46
@nicolebottoms - How sad! I'm pretty sure I've camped there before. Curious, if the park does re-open, are we then able to reset it in the system? Or would another process be needed?

**Comment by cameronpettit** [comment] 2024-12-06 00:19
@LindsayMacfarlane good catch. Just looking into this now. It has been a long time since I looked at A&R projects but if I recall correctly, the system doesn't support this concept of making a park 'historical'.  There's a really long chain of information I managed to dig up from this ticket: https://github.com/bcgov/bcparks-ar-admin/issues/250.

The summary of it is: we only have the capability to set data items to the `legacy` status. The `legacy` status means something different than `historical` (see the link above). We can't set parks to `legacy`, its a data restriction. Only subareas can do this - which we can do, but I am not sure it's really what the intent of this ticket is. 

@nicolebottoms It sounds like what we want here is the ability to prevent people from entering data in certain parks, essentially 'turning them off', so that they are still in the system, but do not collect data. Is that correct? I think this ability is not something we currently have in A&R (@davidclaveau @Christopher-walsh22 correct me if I'm wrong). Our existing `isLegacy` flag does not serve this purpose.

**Comment by cameronpettit** [comment] 2024-12-06 19:34
@nicolebottoms if you remove role access from everyone who has the `attendance-and-revenue: 0063:0153` role, this will prevent those users from being able to pull up that subarea. `sysadmins` will still have access. No further action required, no need to change the bundle I don't think. Unless you want that change to happen too. 

If this is going to happen often we should maybe consider looking into some feature that 'closes' data entry for a subarea - that is, you can toggle whether or not you can enter data for a specific subarea, but turning the subarea back on after closing it doesn't let you go back to the years/months it was closed and enter data again.

**Comment by cameronpettit** [comment] 2024-12-06 19:39
@nicolebottoms @LindsayMacfarlane @davidclaveau potentially new problem - if you remove role access as described in my previous comment AND that was the user's only A&R role then they will no longer have access to any part of the system. Will that be an issue?

**Comment by nicolebottoms** [comment] 2024-12-06 23:10
in this instance i can't see a case where somebody would only have access to goldpan park, so not an issue here.

**Comment by nicolebottoms** [comment] 2024-12-10 18:03
hey for sure that works for me.

**Comment by cameronpettit** [comment] 2024-12-10 19:30
@nicolebottoms yeah that would be the idea. If we actually decide to implement something like this we'll do a little more investigation on how it might look beforehand.

In the meantime, this change is done in PROD - Goldpan subarea is now marked as historic.

**Comment by manuji** [comment] 2024-12-11 20:40
Tested on TEST and PROD: **Passed**
* Verified that this change request has been completed on PROD and TEST environments. 
* Moving to PO review.

**Comment by LindsayMacfarlane** [comment] 2024-12-12 19:08
Confirmed in test. approved. 

Thanks for your thoughtful work on this one @cameronpettit !

**Closed by LindsayMacfarlane** 2024-12-12 19:08 UTC
Labels: A&R
